version: '2'

services:


  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - /home/sdiaz/vituin_project/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /home/sdiaz/vituin_project/elasticsearch/data/:/usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  kibana:
    build:
      context: kibana/
    volumes:
      - /home/sdiaz/vituin_project/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch


  postgres:
     image: postgres:9.6
     environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
     networks:
      - elk
  airflow:
      build: airflow/
      volumes:
      - /home/sdiaz/vituin_project/airflow/data_analysis:/usr/local/airflow/data_analysis
      - /home/sdiaz/vituin_project/airflow/dags:/usr/local/airflow/dags
      restart: always
      depends_on:
          - postgres
      environment:
          - LOAD_EX=y
      ports:
          - "8080:8080"
      command: webserver
      networks:
          - elk

  dashboard:
      build: dashboard/
      volumes:
      - /home/sdiaz/dash.conf:/etc/apache2/conf-available/dash.conf
      - /home/sdiaz/extra_components-0.0.1-py2.7.egg:/usr/local/lib/python2.7/dist-packages/
      - /home/sdiaz/vituin_project/dashboard/vituin_dashboard/web:/var/www/html
      - /home/sdiaz/vituin_project/dashboard/vituin_dashboard/graficas:/var/local/plotly
      ports:
          - "80:80"
          - "8050:8050"
      networks:
          - elk

networks:

  elk:
    driver: bridge





