version: '2'

services:


  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - /home/sdiaz/vituin_project/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  kibana:
    build:
      context: kibana/
    volumes:
      - /home/sdiaz/vituin_project/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch


  postgres:
     image: postgres:9.6
     environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
     networks:
      - elk
  airflow:
      build: airflow/
      volumes:
      - /home/sdiaz/vituin_project/airflow/scrapy:/usr/local/airflow/scrapy-hotels
      - /home/sdiaz/vituin_project/airflow/dags:/usr/local/airflow/dags
      restart: always
      depends_on:
          - postgres
      environment:
          - LOAD_EX=y
      ports:
          - "8080:8080"
      command: webserver
      networks:
          - elk

networks:

  elk:
    driver: bridge





