version: '3.2'

services:
  elasticsearch:
    imagen: elasticsearch:6.5.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    image: kibana:6.5.1
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  postgres:
     image: postgres:9.6
     environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  airflow:
      build: airflow/
      volumes:
      - /home/sdiaz/vituin_project/airflow/data_analysis:/usr/local/airflow/data_analysis
      - /home/sdiaz/vituin_project/airflow/dags:/usr/local/airflow/dags
      restart: always
      depends_on:
          - postgres
      environment:
          - LOAD_EX=y
      ports:
          - "8080:8080"
      command: webserver

  dashboard:
      build: dashboard/
      volumes:
      - /home/sdiaz/dash.conf:/etc/apache2/conf-available/dash.conf
      - /home/sdiaz/extra_components-0.0.1-py2.7.egg:/usr/local/lib/python2.7/dist-packages/
      - /home/sdiaz/vituin_project/dashboard/vituin_dashboard/web:/var/www/html
      - /home/sdiaz/vituin_project/dashboard/vituin_dashboard/graficas:/var/local/plotly
      ports:
          - "80:80"
          - "8050:8050"
