version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0 
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.0
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  airflow:
    build: airflow/
    volumes:
      - ./airflow/data_analysis:/usr/local/airflow/data_analysis
      - ./airflow/dags:/usr/local/airflow/dags
    restart: always
    environment:
      - LOAD_EX=y
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - postgres

  dashboard:
    build:
      context: dashboard/
      dockerfile: Dockerfile
    volumes:
      - ./dashboard/config:/home/vituin-dashboard/instance:ro
    command: ["./wait-for-elasticsearch.sh", "http://elasticsearch:9200", "--", "./boot.sh"]
    environment:
      WEB_CONCURRENCY: 17
      VITUIN_DASHBOARD_SETTINGS: vituin_dashboard.conf
    expose:
      - "5000"
    depends_on:
      - elasticsearch

  nginx:
    restart: always
    build:
      context: dashboard/
      dockerfile: Dockerfile.nginx
    ports:
      - 0.0.0.0:80:80
    depends_on:
      - dashboard

