---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kib$
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200




